export const BUBBLE_TYPE = 'bubble';
export const CONNECTOR_TYPE = 'connector'
export const SELECT_CONNECTOR = 'select-connector'
export const SEND_MESSAGE = 'send-message'
export const SET_ACCOUNT = 'set-account'
export const SELECT_CHAT_WITH = 'select-chat-WITH'
export const ON_MESSAGE = 'on-message'
export const ON_FEEDBACK = 'on-feedback'

export const SOCKET_STATUS_CONNECT = 'connect'
export const SOCKET_STATUS_CONNECT_ERROR = 'connect_error'
export const SOCKET_STATUS_CONNECT_TIMEOUT = 'connect_timeout'
export const SOCKET_STATUS_RECONNECT = 'reconnect'
export const SOCKET_STATUS_RECONNECT_ATTEMPT = 'reconnect_attempt'
export const SOCKET_STATUS_RECONNECTING = 'reconnecting'
export const SOCKET_STATUS_RECONNECT_ERROR = 'reconnect_error'
export const SOCKET_STATUS_RECONNECT_FAILED = 'reconnect_failed'
